baseURL = 'https://aitumik.github.io'
languageCode = 'en-us'
title = 'Nate'
theme = 'puppet'
publishDir = 'public'

copyright = ""
paginate = 3
defaultContentLanguage = "en"

hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

disqusShortname = ""
googleAnalytics = ""

[outputs]
home = ["HTML", "JSON", "RSS"]

# prevent build failures when using Hugo's template _internal/opengraph.html 
[taxonomies]
category = "categories"
tag = "tags"
series = "series"
politics = "politics"

[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archive/"
weight = 10
[[menu.main]]
identifier = "guide"
name = "Guide"
url = "/series/themes-guide/"
weight = 20
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 50
[[menu.main]]
identifier = "github"
name = "Github"
url = "https://github.com/aitumik"
weight = 100


[params]
author = "Puppet"
description = "Software Engineer | Computer Prorgrammer"
keywords = "blog,developer,personal"
img_home = "img/home-bg.jpg"
img_404 = "img/404-bg.jpg"

useFaviconGenerator = true

custom_js = []
custom_css = [] # ["css/custom.css"]  Add your file to assets folder  [assets/css/custom.css]

[params.sidebar]
enable = true
gravatarEmail = ""
# Overwritten by your gravatar image if `gravatarEmail` is filled
avatar = "img/home-bg.jpg"
bio = "I will say what I want"

[params.social]
twitter = "aitumik"
github = "aitumik"
linkedin = "nathan_kimutai"
rss = true

# See https://giscus.app/
[params.giscus]
enable = false
repo = "roninro/hugo-theme-puppet"
repo_id = "R_kgDOHuvyhw"
category = "General"
category_id = "DIC_kwDOHuvyh84CQjDo"
input_position = "top"
theme = "light_tritanopia"
lang = "en"